### ISSUE TITLE
Italian provinces gives null

### ISSUE THREAD

**Issue by JEricaM** [i-rocky/country-list-js#58]
Hi

I'm the girl who some time ago made a [PR](https://github.com/i-rocky/country-list-js/pull/55) about adding Italian provinces. 
Finally today I was able to return on the project where I need the provinces that I've added.
I've updated the library and tried to retrieve all the states using 'countries.all,' and I noticed that in the Italian state, the 'provinces' key is still null. Is there any issue with the feature? I'm using version 3.1.7, which I also see is the latest in the package.

Thanks

**Comment by JEricaM** [comment]
Thank you!

**Comment by ekkis** [comment]
ok.  it was complicated.  I tried to fix the audit report for vulnerabilities but there were ABCs so I had to --force.  NPM is broken so it wanted to downgrade a number of packages.  I had to upgrade npm/node to the latest versions but it didn't ix it.  then I had issues with tags.  anyway, I've published v3.1.8, which I believe contains your changes.  I've also reformatted the json files so that contributions can be diffed more easily.  I'll need to figure out how minify them for production.  later
